// "On Trend" brief: what is moving in the brand's category right now, the
// dated moments coming up, the pop-culture beats worth riding, and concrete
// content ideas per channel. Generated by Claude with live web search, once a
// day per client, stored in the client's private sheet. Nothing here is
// shared between clients — the prompt is built from each profile.
import Anthropic from '@anthropic-ai/sdk';
import { getClient } from '@/src/lib/client';
import { loadDoc, saveDoc } from '@/src/lib/docStore';
import { todayPst } from '@/src/lib/timeframes';

export interface TrendItem { title: string; why: string; angle?: string; date?: string }
export interface ContentIdea { hook: string; format: string; cta?: string }
export interface TrendBrief {
  generatedAt: string;
  asOf: string;
  headline: string;
  now: TrendItem[];
  upcoming: TrendItem[];
  popCulture: TrendItem[];
  ideas: { social: ContentIdea[]; email: ContentIdea[]; sms: ContentIdea[] };
  sources: { title: string; url: string }[];
}

const DOC = 'trend_brief';
export const TREND_TTL_MS = 24 * 60 * 60 * 1000;

let memory: TrendBrief | null = null;

export async function loadTrendBrief(): Promise<TrendBrief | null> {
  if (memory) return memory;
  try {
    const raw = await loadDoc(DOC);
    if (raw) { memory = JSON.parse(raw) as TrendBrief; return memory; }
  } catch { /* sheet not configured or unreadable — treat as no brief */ }
  return null;
}

export function isStale(b: TrendBrief | null): boolean {
  return !b || Date.now() - Date.parse(b.generatedAt) > TREND_TTL_MS;
}

function extractJson(text: string): unknown {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  const candidate = fenced ? fenced[1] : text.slice(text.indexOf('{'), text.lastIndexOf('}') + 1);
  return JSON.parse(candidate);
}

export async function generateTrendBrief(): Promise<TrendBrief> {
  const apiKey = (process.env.ANTHROPIC_API_KEY || '').trim();
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY not configured');
  const client = new Anthropic({ apiKey });
  const c = getClient();
  const today = todayPst();

  const prompt = `Today is ${today}. You are the trend scout for ${c.name}.

BRAND: ${c.brand.description}
CONTENT WE ALREADY LEAN ON: ${c.brand.contentAngles}

Use web search to find what is genuinely current — the last 2-3 weeks of coverage and the next 6 weeks of the calendar. Search several angles: the category's fashion/aesthetic trends, viral social formats and sounds the audience is using, upcoming dated moments (seasonal shifts, holidays, award shows, fashion weeks, big releases, celebrity engagements and weddings, TV and film the audience is watching), and what competitors or adjacent brands are doing that is getting traction. Prefer named, specific, sourced things over generic advice. Skip anything older than a month unless it is still peaking.

Return ONLY a JSON object (no prose around it) with this exact shape:
{
  "asOf": "${today}",
  "headline": "one sentence: the single biggest thing this brand should be on right now",
  "now": [ { "title": "…", "why": "1-2 sentences on what it is and the evidence it is peaking", "angle": "how ${c.name} rides it, in one sentence" } ],   // 4-6 items
  "upcoming": [ { "date": "YYYY-MM-DD or a range", "title": "…", "why": "…", "angle": "…" } ],   // 4-6 dated moments, soonest first
  "popCulture": [ { "title": "…", "why": "why the 25-34 audience cares this week", "angle": "…" } ],   // 3-5 items
  "ideas": {
    "social": [ { "hook": "the first line / on-screen text", "format": "Reel, carousel, TikTok, story, UGC…", "cta": "…" } ],   // 4 ideas
    "email":  [ { "hook": "subject line", "format": "campaign type", "cta": "…" } ],   // 3 ideas
    "sms":    [ { "hook": "the text, under 160 chars", "format": "…", "cta": "…" } ]   // 2 ideas
  },
  "sources": [ { "title": "…", "url": "…" } ]   // the pages you actually relied on, up to 8
}`;

  const response = await client.messages.create({
    model: 'claude-opus-5',
    max_tokens: 16000,
    thinking: { type: 'adaptive' },
    tools: [{ type: 'web_search_20260209', name: 'web_search', max_uses: 10 } as unknown as Anthropic.Tool],
    messages: [{ role: 'user', content: prompt }],
  });
  if (response.stop_reason === 'refusal') throw new Error('The model declined to build the brief; try again later.');

  // Collect text and the searched pages (for the sources list fallback).
  let text = '';
  const seen: { title: string; url: string }[] = [];
  for (const block of response.content as unknown as Array<Record<string, unknown>>) {
    if (block.type === 'text') text += String(block.text || '');
    if (block.type === 'web_search_tool_result' && Array.isArray(block.content)) {
      for (const r of block.content as Array<Record<string, unknown>>) {
        if (r.type === 'web_search_result' && typeof r.url === 'string') seen.push({ title: String(r.title || r.url), url: r.url });
      }
    }
  }
  const parsed = extractJson(text) as Partial<TrendBrief>;
  const arr = <T,>(v: unknown): T[] => (Array.isArray(v) ? (v as T[]) : []);
  const brief: TrendBrief = {
    generatedAt: new Date().toISOString(),
    asOf: parsed.asOf || today,
    headline: parsed.headline || '',
    now: arr<TrendItem>(parsed.now).slice(0, 6),
    upcoming: arr<TrendItem>(parsed.upcoming).slice(0, 6),
    popCulture: arr<TrendItem>(parsed.popCulture).slice(0, 5),
    ideas: {
      social: arr<ContentIdea>(parsed.ideas?.social).slice(0, 4),
      email: arr<ContentIdea>(parsed.ideas?.email).slice(0, 3),
      sms: arr<ContentIdea>(parsed.ideas?.sms).slice(0, 2),
    },
    sources: (arr<{ title: string; url: string }>(parsed.sources).length ? arr<{ title: string; url: string }>(parsed.sources) : seen).slice(0, 8),
  };
  memory = brief;
  try { await saveDoc(DOC, JSON.stringify(brief)); } catch { /* sheet not configured — memory copy still serves this instance */ }
  return brief;
}
